### ISSUE TITLE
ROS2 release

### ISSUE THREAD

**Issue by HappySamuel** [NaokiAkai/als_ros#10]
Hi

Is there any ROS2 release for als_ros? I would like to try it out with ROS2.

Best,
Samuel

**Comment by NaokiAkai** [comment]
Hi Samuel,

I am planning to release ROS2-based implementation of als_ros; however, I am unable to make any prediction when I can release it.

Best,
Naoki

**Comment by NaokiAkai** [comment]
Hi Samuel,

I am planning to release ROS2-based implementation of als_ros; however, I am unable to make any prediction when I can release it.

Best,
Naoki
