### ISSUE TITLE
where is local_map_name published?

### ISSUE THREAD

**Issue by Burakzdd** [NaokiAkai/als_ros#11]

**Comment by NaokiAkai** [comment]
Hi Burakzdd,

Can you give me more details?

Do you want to know what the node publishes the local map for global localization? If so, the gl_pose_sampler node publishes the local map.

**Comment by Burakzdd** [comment]
Okay, thanks. I have another question, I want to spread the poses on the map. What can I do?

**Comment by NaokiAkai** [comment]
> Okay, thanks. I have another question, I want to spread the poses on the map. What can I do?

You can subscribe the occupancy grid map and can know the free space where a robot can exist. You can make poses on the free space and can publish poses as global localization particles.

**Comment by Burakzdd** [comment]
Okay, i'll try, thanks for everything :)
