### ISSUE TITLE
localization issues

### ISSUE THREAD

**Issue by eithwa** [NaokiAkai/als_ros#12]
hi,
In my test, the robot tf will move to the wrong place, and the reliability value has been maintained at 99.99%, what parameters should I change?
thanks
video:
[![test video](http://img.youtube.com/vi/qRe-P6Xyadg/0.jpg)](http://www.youtube.com/watch?v=qRe-P6Xyadg)
bagfile and map : 
https://drive.google.com/drive/folders/1Fd11c5NSgx-NSjXd_ZWah2CLNwzLm-2k?usp=share_link
```
<node pkg="tf" type="static_transform_publisher" name="base_link_2_laser" args="0.06 0 0 0 0 0 /base_link /laser 100"/>
```

**Comment by Nikhil619** [comment]
Hey did you solve it??

**Comment by Nikhil619** [comment]
Please post your launch file

**Comment by eithwa** [comment]
> Please post your launch file

Thank you for your reply
Here is the link to the launch file that I missed
https://drive.google.com/file/d/182XzIdMi3RTf0RPdy4MBUMd0D3Ob8Rcc/view?usp=share_link

**Comment by Nikhil619** [comment]
![Screenshot_2023-02-27-01-30-49-57_e2d5b3f32b79de1d45acd1fad96fbb0f.jpg](https://user-images.githubusercontent.com/67323988/221434037-183a3571-2764-4096-bf37-43847524501b.jpg)

Hey, I don't think this is a launch file

**Comment by eithwa** [comment]
Sorry, I uploaded it to gist
https://gist.github.com/eithwa/4d3dcf0feb734751d5fcaa196e40f176

**Comment by Nikhil619** [comment]
Did you set global_pose_sampler to True or False?

**Comment by Nikhil619** [comment]
<arg name="matching_rate_th" default="0.03" />

Setting use_global_pose_sampler to false could solve this. But if you want the global_pose_sampler to be there then try adjusting the above mentioned parameter. In the video it's clear that the algorithm tried to match the scan with another similar part of the map. So adjusting this parameter could help

**Comment by Nikhil619** [comment]
Did you try?

**Comment by eithwa** [comment]
> Did you try? If it's working fine without global localisation please close the issue.

Sorry for the late reply
Now it works normally after turning off the global localization
thank you
close issue
