### ISSUE TITLE
Any Description regarding SLAMMER

### ISSUE THREAD

**Issue by HappySamuel** [NaokiAkai/als_ros#13]
Hi

I found that there's newly added slammer node, but i couldn't find any description / elaboration regarding this slammer node. Can briefly explain what's it functions?

Best,
Samuel

**Comment by NaokiAkai** [comment]
I am sorry for my late reply. Actually, I don't plan that I officially support SLAMER in this package. Please see the arXiv preprint for more details.
https://arxiv.org/abs/2207.09909

**Comment by HappySamuel** [comment]
OK, thanks for the clarification.

Best,
Samuel
