### ISSUE TITLE
How to get the initial pose

### ISSUE THREAD

**Issue by guanba666** [NaokiAkai/als_ros#16]
hello，How to get the initial pose?Does the algorithm have relocation capabilities？
thanks！

**Comment by NaokiAkai** [comment]
I'm sorry, I cannot understand your problem. You can set the initial pose at mcl.launch. Also, you can give als_ros an initial pose from rviz.

**Comment by li9i** [comment]
Hello @NaokiAkai. Thank you very much for your work. I think perhaps the first part of @guanba666's question meant to enquire about the triggering of global localisation. Is it possible to use `als_ros` in order to estimate the robot's pose from no information other than the map and a scan?

**Comment by NaokiAkai** [comment]
@li9i 
als_ros does not have a trigger to perform the global localization and always performs global localization if the global localization flag is true. To perform the global localization, a map and scan data are necessary. Details of the fusion of local pose tracking and global localization can be seen at the paper.
https://arxiv.org/abs/2205.04769
