### ISSUE TITLE
Is there any plans to port this over to ROS2?

### ISSUE THREAD

**Issue by benripka** [NaokiAkai/als_ros#17]
Hi there, great work on this. Wondering if you have any plans to port this over to ROS2 given ROS's upcoming deprecation? Just curious. Cheers.

**Comment by NaokiAkai** [comment]
Thanks! I am planning to make a ROS2 node of this package. However, I cannot say its exact schedule.

**Comment by benripka** [comment]
Weeuw Go @NaokiAkai 🥳

**Comment by InguChoi** [comment]
@NaokiAkai So, is the package for ROS2 available?
