### ISSUE TITLE
Estimating pose drift

### ISSUE THREAD

**Issue by voladorfly** [NaokiAkai/als_ros#18]
People block part of the laser, and the position keeps changing.How to deal with it？

**Comment by NaokiAkai** [comment]
Sorry, I cannot imagine well what kind of a problem do you have now. Can you please share more details?

**Comment by voladorfly** [comment]
Details：
![output1](https://github.com/NaokiAkai/als_ros/assets/15795565/1acf0038-b34f-441a-a582-ce26009e816b)

**Comment by NaokiAkai** [comment]
Seems you are updating a map based on the localization result. If so, als_ros does not work since random particles are injected in the resampling phase. At least, you need to set add_random_particles_in_resampling to false. However, als_ros does not support a map update case.

**Comment by voladorfly** [comment]
Thanks, I'll read the code carefully again！

**Comment by NaokiAkai** [comment]
I close this issue.
