### ISSUE TITLE
Does not work with upside down LiDAR (Robot Pose Drifting and Oscillating)

### ISSUE THREAD

**Issue by David9696** [NaokiAkai/als_ros#4]
Hi,

Thanks for sharing this project. I have tried to implement this package to my robot. Once my robot is moving, the localized pose starts to drift and oscillate. May I know what is the problem? Could it because my lidar is mounted upside down(inverted)?

**Comment by NaokiAkai** [comment]
You need to correctly set static transformation from the base link to your laser sensor. If your sensor is mounted upside down, you have to set appropriate rotation angles.

**Comment by NaokiAkai** [comment]
als_ros does not correspond to upside down mount. Please make a new node which virtually makes laser scan obtained from a normal mounted sensor.

**Comment by NaokiAkai** [comment]
close

**Comment by HappySamuel** [comment]
Hi @David9696 

If you want to use a lidar that is mounted upside down, you will need to have a correct TF that connected lidar and robot's base frame. Next, you can transform original lidar scan's frame into another frame. Finally your new transformed scan can be used with als_ros already.

Best,
Samuel
