### ISSUE TITLE
High CPU usage for gl_pose_sampler and mrf_failure_detector node

### ISSUE THREAD

**Issue by David9696** [NaokiAkai/als_ros#5]
Hi,

I have implemented this package in a simulated robot. With use_mrf_failure_detector:=true and  use_gl_pose_sampler:=true , I realised that the gl_pose_sampler and mrf_failure_detector nodes would consumes a lot of cpu, about 100% for two cpu cores. Is this normal? Is there a way to reduce the cpu usage?

Thanks.

**Comment by NaokiAkai** [comment]
> Hi,
> 
> I have implemented this package in a simulated robot. With use_mrf_failure_detector:=true and use_gl_pose_sampler:=true , I realised that the gl_pose_sampler and mrf_failure_detector nodes would consumes a lot of cpu, about 100% for two cpu cores. Is this normal? Is there a way to reduce the cpu usage?
> 
> Thanks.

**Comment by NaokiAkai** [comment]
Thank you for pointing out it. I have updated to reduce the computational cost of MRF failure detector. In new mrf_failure_detector.launch, max_residual_errors_num (default is 500) is added. Please reduce this value if the computational cost is still high.

To reduce the cost of the gl pose sampler, please set to a small value to key_scans_num. If you use long range LiDAR, it might difficult to reduce the key scan num. If so, making short range scan could be one of possible solution. Or, reduce the map resolution might also be effective.

**Comment by David9696** [comment]
Hi @NaokiAkai,

Thanks for your update. Yes, the computational cost is lower when I reduce the max_residual_errors_num. Now is about 25% of CPU usage which is more normal.

Secondly, for gl pose sampler, it seems like there is no way to reduce the computational cost. I have tested with reduced key scan num, reduced the scan range to 5m and reduced the map resolution, but the computational cost is still hitting 100% for a cpu core. Is there anything else that I can tune?

**Comment by NaokiAkai** [comment]
Hi @David9696 ,
Actually, there are no effective ways to reduce the cost for gl pose sampler. But, I have never met with such cases. Can you share with me some data?

**Comment by David9696** [comment]
Hi @NaokiAkai,

Thanks for your reply. I could provide a rosbag file. Is it useful for you?

The map I used is 164.3 kb in size. The required map file is attached with this reply. Hope it is useful.

[map.zip](https://github.com/NaokiAkai/als_ros/files/8747634/map.zip)

**Comment by NaokiAkai** [comment]
@David9696 
Thank you for sharing the files! I will check them soon.

Actually, I cannot have methods to reduce the computational cost for the gl pose sampler now. I will try to find some ways to reduce it based on your data.

**Comment by David9696** [comment]
Hi @NaokiAkai,

Thanks for your reply.

Some updates from my side. On a different robot, I regenerated a new 2D map and tested with  gl pose sampler node, surprisingly, it is only consuming 5% of cpu core. To me, this is more normal. Not sure where is the problem. Do you need a bag file to check? The mcl node and MRF failure detector node are using 25% and 23% CPU core respectively. Is it normal?

**Comment by NaokiAkai** [comment]
@David9696
I have tested with your data. Actually, I did not have the computational cost problem. Can you share with me the rosbag file corresponding to map.zip?

**Comment by David9696** [comment]
Hi @NaokiAkai ,

I have tested a few days and I could not reproduce the issue anymore. What I have done was I deleted the devel and build folder and catkin_make the ws again. Not sure whether it really helps. Now, everything is working as per normal. I will close this issue for the time being. Thanks for your great help and sharing this great package.
