### ISSUE TITLE
Could not use als_ros with navigation stack

### ISSUE THREAD

**Issue by atinfinity** [NaokiAkai/als_ros#6]
## System information

- Ubuntu 18.04
- ROS Melodic

## Detailed description

I hope to replace amcl with als_ros. So, I tried on Gazebo simulator.
But it occurs the following error.

```shell
[ INFO] [1654619677.594540743, 18.175000000]: Got new plan
[ERROR] [1654619677.594762760, 18.176000000]: Extrapolation Error: Lookup would require extrapolation into the future.  Requested time 18.151000000 but the latest data is at time 17.952000000, when looking up transform from frame [odom] to frame [map]

[ERROR] [1654619677.594791175, 18.176000000]: Global Frame: odom Plan Frame size 89: map
```

### Disable AMCL

I changed `/opt/ros/melodic/share/turtlebot3_navigation/launch/turtlebot3_navigation.launch` to disable amcl.

### Launch Gazezbo

```
roslaunch turtlebot3_gazebo turtlebot3_world.launch
```

### Launch als_ros

```shell
roslaunch als_ros mcl.launch laser_frame:=base_scan
```

### Launch turtlebot3_navigation

```shell
roslaunch turtlebot3_navigation turtlebot3_navigation.launch
```

## Investigation

The amcl has `transform_tolerance` to transform the coordinate system using tf.

- <https://github.com/ros-planning/navigation/blob/1.16.7/amcl/src/amcl_node.cpp#L1465-L1469>
- <http://wiki.ros.org/amcl>

But, it seems that als_ros does not have this parameter.
<https://github.com/NaokiAkai/als_ros/blob/15349fd6d9f4c287d7e154ebcc14ee9cb7ba40a6/src/als_ros/include/als_ros/MCL.h#L514>

So, I changed als_ros to resolve this problem.

```diff
--- a/src/als_ros/include/als_ros/MCL.h
+++ b/src/als_ros/include/als_ros/MCL.h
@@ -511,7 +511,8 @@ public:
         if (rejectUnknownScan_ && (measurementModelType_ == 0 || measurementModelType_ == 1))
             rejectUnknownScan();
 
-        mclPoseStamp_ = scan_.header.stamp;
+        ros::Duration transform_tolerance(1.0); // TODO: This value should be set as a parameter.
+        mclPoseStamp_ = scan_.header.stamp + transform_tolerance;
```

As a result, I could use als_ros with navigation stack.

**Comment by NaokiAkai** [comment]
@atinfinity 
Thank you for pointing out its problem. I will update als_ros to fix it soon and close this issue.
